name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rotten:$GITHUB_SHA
    - name: Test output
      run: docker run --rm -e API_KEY={{ secrets.API_KEY }} rotten:$GITHUB_SHA "Guardians of the Galaxy Vol. 2"
